// SPDX-License-Identifier: BSD-3-Clause
// mixer_asm end-to-end test harness — buffer layout mirrors NXP's cwproj
// driver (submodules/.../mixer/mixer_cwproj/Sources/main.c) so the asm
// sees identical inputs and writes the same outputs.
//
// `mixer_asm(py, px, PhaseIn, FreqIn, L)` performs
//   y[k] = x[k] * exp(+2πj·(FreqIn/2^32)·(PhaseIn + k))
// on `L` lines of `__AU_COUNT__*2` complex 16-bit half-fixed samples.
// Reference is generated by the bit-exact Python r_nco/r_smad oracle
// (verify_mixer.py is green against NXP golden vectors).
//
// Note: vspa.h is suppressed via -D__VSPA_H__ at the compile flag level
// to avoid an `_VR` macro redefinition: mixer_asm.sx itself includes
// vspa.h and then redefines _VR locally, which fsvspacc rejects under
// `-msgstyle gcc`. Predefining the include guard makes the .sx-side
// include of vspa.h a no-op; the local _VR/_VRH definitions on lines
// 44-45 of mixer_asm.sx then stand alone. The C harness gets vector
// alignment from <vspa/intrinsics.h> via test_utils.h.

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <vspa/intrinsics.h>
#include "test_utils.h"

typedef __fx16 fixed16_t;
typedef struct { fixed16_t real; fixed16_t imag; } cfixed16_t;

extern unsigned int mixer_asm(cfixed16_t *py, cfixed16_t *px,
                              uint32_t PhaseIn, int FreqIn, size_t L);

// Match cwproj test config: L lines × (__AU_COUNT__*2) complex samples.
#define LINES   2
#define N_CPLX  (LINES * (__AU_COUNT__ * 2))   // complex samples
#define N_HW    (2 * N_CPLX)                    // halfwords (re,im,...)

// Mixer parameters — gen_vectors.py uses the matching values.
#define PHASE_IN 0x12345678u
#define FREQ_IN  0x00123456    // signed; positive => no 1's-comp flip

// Inputs / reference loaded from gen_vectors.py output (one halfword
// per line, interleaved real/imag, sign-magnitude SM16 encoding).
static const int16_t INPUT_DATA[N_HW] = {
#include "vectors/input.hex"
};
static const int16_t REF_DATA[N_HW] = {
#include "vectors/ref.hex"
};

// Mirror cwproj: vector-aligned, BSS-resident (zero-initialised) buffers.
_VSPA_VECTOR_ALIGN static int16_t MIXER_INP_BUFF[N_HW];
_VSPA_VECTOR_ALIGN static int16_t MIXER_OUT_BUFF[N_HW];

int main(void)
{
    int i;

    // Stage input into the dedicated input buffer (cwproj mem_copy).
    for (i = 0; i < N_HW; i++)
        MIXER_INP_BUFF[i] = INPUT_DATA[i];

    // Measure only the kernel body (honest cycle count, not whole-program).
    KCYC_INIT();
    KCYC_START();
    (void)mixer_asm((cfixed16_t *)MIXER_OUT_BUFF,
                    (cfixed16_t *)MIXER_INP_BUFF,
                    PHASE_IN, FREQ_IN, LINES);
    KCYC_STOP_PRINT();

    return vspa_array_cmp((const unsigned *)MIXER_OUT_BUFF,
                          (const unsigned *)REF_DATA,
                          N_CPLX);
}
