// SPDX-License-Identifier: BSD-3-Clause
// matrix (mat_bmult batch matrix-vector multiply) end-to-end test harness.
// Wiring mirrors NXP's cwproj driver:
//   submodules/la931x_vspa_common/vspa-lib/matrix/matrix_cwproj/src/main.c
//
// cwproj allocates three vector-aligned buffers in BSS, copies test data in
// at runtime, and calls the wrapper `mat_bmult(vec, mat, out, D1, D2, D3)`,
// which dispatches by `dim2`:
//     dim2 == 1  →  mat_bmult_d1x1xd3_chfx_csp_chfl_asm
//     dim2 == 2  →  mat_bmult_d1x2xd3_chfx_csp_chfl_asm
//     dim2 >= 3  →  mat_bmult_64xd2xd3_chfx_csp_chfl_asm  (D1 must equal 64)
//
// This harness pins the configuration to cwproj TC043 (D1=64, D2=1, D3=1,
// mat_interp=1, vec=half_fixed, mat=single, out=half) — the simplest
// half_fixed×single→half case, dispatching to `mat_bmult_d1x1xd3_chfx`.
//
// The buffers are sized to MATRIX_TEST_*_MAX (matching cwproj exactly) so
// extending to a different TC is a matter of changing the *_RUN dimensions.

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include "test_utils.h"  // <vspa/intrinsics.h> + vspa_array_cmp()

// We deliberately do NOT include "matrix.h" / "vcpu.h" here:
//   - vcpu.h declares `void main(void) __noreturn`, which collides with our
//     `int main(void)` that returns to the run_test.py harness.
//   - matrix.h's prototypes use cfixed16_t/cfloat16_t/cfloat32_t, but the
//     actual asm functions only care about the underlying memory layout
//     (interleaved halfwords). Forward-declaring them with void* is
//     sufficient and is what every other test in tests/* does.
//
// Wrapper signature mirrors matrix_bmult_c.c exactly.
typedef enum { MAT_BMULT_SUCCESS = 0, MAT_BMULT_ERROR } MAT_BMULT_RETURN_T;

extern MAT_BMULT_RETURN_T mat_bmult_chfx_csp_chfl_c(
        void *vec_p, void *mat_p, void *out_p,
        uint32_t dim1, uint32_t dim2, uint32_t dim3);

// ---------------------------------------------------------------------------
// cwproj-aligned buffer sizing (MATRIX_TEST_*_MAX, same numerical values).
// ---------------------------------------------------------------------------
#define MATRIX_TEST_VEC_DIM1_MAX 64
#define MATRIX_TEST_MAT_DIM1_MAX 64
#define MATRIX_TEST_DIM2_MAX     4
#define MATRIX_TEST_DIM3_MAX     8

// Per-run dimensions — pinned to cwproj TC043.
#define DIM1_RUN 64
#define DIM2_RUN 1
#define DIM3_RUN 1

#define VEC_LEN_COMPLEX (DIM1_RUN * DIM2_RUN)             // 64
#define MAT_LEN_COMPLEX (DIM1_RUN * DIM3_RUN * DIM2_RUN)  // 64
#define OUT_LEN_COMPLEX (DIM1_RUN * DIM3_RUN)             // 64

// ---------------------------------------------------------------------------
// Embedded test vectors (generated by gen_vectors.py).
// ---------------------------------------------------------------------------
//
// vec.hex : VEC_LEN_COMPLEX uint32 words, each = (im_sm16<<16)|re_sm16.
// mat.hex : 2 * MAT_LEN_COMPLEX uint32 words, interleaved [re_f32_bits, im_f32_bits].
// ref.hex : OUT_LEN_COMPLEX uint32 words, each = (im_f16_bits<<16)|re_f16_bits.
static const unsigned VEC_DATA[VEC_LEN_COMPLEX] = {
#include "vectors/vec.hex"
};

static const unsigned MAT_DATA[2 * MAT_LEN_COMPLEX] = {
#include "vectors/mat.hex"
};

static const unsigned REF_DATA[OUT_LEN_COMPLEX] = {
#include "vectors/ref.hex"
};

// ---------------------------------------------------------------------------
// Match cwproj BSS-resident, vector-aligned buffers (sized to MAX).
// One uint32 word holds one packed cfixed16_t (vec) or cfloat16_t (out).
// MAT buffer holds cfloat32_t — 2 uint32 words per complex sample.
// ---------------------------------------------------------------------------
_VSPA_VECTOR_ALIGN static unsigned VEC_BUFF
        [MATRIX_TEST_VEC_DIM1_MAX * MATRIX_TEST_DIM2_MAX];
_VSPA_VECTOR_ALIGN static unsigned MAT_BUFF
        [2 * MATRIX_TEST_MAT_DIM1_MAX * MATRIX_TEST_DIM3_MAX * MATRIX_TEST_DIM2_MAX];
_VSPA_VECTOR_ALIGN static unsigned OUT_BUFF
        [MATRIX_TEST_VEC_DIM1_MAX * MATRIX_TEST_DIM3_MAX];

int main(void)
{
    int i;

    // Stage inputs into the start of the BSS-zero buffers (mirrors cwproj's
    // mem_copy from the testbench's per-TC binary loaders).
    for (i = 0; i < VEC_LEN_COMPLEX; i++)
        VEC_BUFF[i] = VEC_DATA[i];
    for (i = 0; i < 2 * MAT_LEN_COMPLEX; i++)
        MAT_BUFF[i] = MAT_DATA[i];

    // mat_bmult wrapper dispatches by dim2; with DIM2_RUN=1 we hit the
    // `mat_bmult_d1x1xd3_chfx_csp_chfl_asm` path. Wrapper returns
    // MAT_BMULT_SUCCESS (=0) on valid params; nonzero indicates a config
    // bug — let it propagate via vspa_array_cmp's mismatch path instead.
    // Measure only the kernel body (honest cycle count, not whole-program).
    KCYC_INIT();
    KCYC_START();
    MAT_BMULT_RETURN_T err = mat_bmult_chfx_csp_chfl_c(
        (void *)VEC_BUFF,
        (void *)MAT_BUFF,
        (void *)OUT_BUFF,
        (uint32_t)DIM1_RUN,
        (uint32_t)DIM2_RUN,
        (uint32_t)DIM3_RUN);
    KCYC_STOP_PRINT();

    if (err != MAT_BMULT_SUCCESS) {
        printf("mat_bmult returned ERROR (%d)\n", (int)err);
        printf("FAIL\n");
        return 1;
    }

    return vspa_array_cmp(OUT_BUFF, REF_DATA, OUT_LEN_COMPLEX);
}
