// SPDX-License-Identifier: BSD-3-Clause
// phcom_asm end-to-end test harness — buffer layout mirrors the cwproj-style
// pattern used by the mixer/cycShiftFD harnesses (no phase_compensation_cwproj
// exists in submodules, so we use the same recipe).
//
// `phcom_asm(sample_out, sample_in, coeff, nL)` performs
//   y[k] = coeff * x[k]
// (single-precision complex multiply, result truncated to half_fixed)
// on `nL` input *lines* of (__AU_COUNT__ * 2) complex 16-bit half-fixed
// samples. `coeff` is a single complex float32 (re, im) — 8-byte aligned.
//
// Reference is generated by the bit-exact Python r_smad/r_half oracle in
// gen_vectors.py.

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <vspa/intrinsics.h>
#include "test_utils.h"

typedef __fx16 fixed16_t;
typedef struct { fixed16_t real; fixed16_t imag; } cfixed16_t;

extern void phcom_asm(void *sample_out, void *sample_in, void *coeff,
                      unsigned int nL);

// Match gen_vectors.py config: nL lines × (__AU_COUNT__*2) complex samples.
#define LINES   1
#define N_CPLX  (LINES * (__AU_COUNT__ * 2))   // complex samples
#define N_HW    (2 * N_CPLX)                    // halfwords (re,im,...)

// Inputs / reference loaded from gen_vectors.py output (one halfword per
// line, interleaved real/imag, sign-magnitude SM16 encoding).
static const int16_t INPUT_DATA[N_HW] = {
#include "vectors/input.hex"
};
static const int16_t REF_DATA[N_HW] = {
#include "vectors/ref.hex"
};

// Complex float32 coeff (re, im) — 8-byte aligned per ABI. gen_vectors.py
// emits coeff.hex with two uint32 IEEE-754 float32 bit patterns.
static const uint32_t COEFF_DATA[2] = {
#include "vectors/coeff.hex"
};

// Mirror cwproj: vector-aligned, BSS-resident (zero-initialised) buffers.
_VSPA_VECTOR_ALIGN static int16_t INP_BUFF[N_HW];
_VSPA_VECTOR_ALIGN static int16_t OUT_BUFF[N_HW];
// __align_vec gives at least 8-byte alignment, sufficient for the 8-byte
// alignment requirement on `coeff`.
_VSPA_VECTOR_ALIGN static uint32_t COEFF_BUFF[2];

int main(void)
{
    int i;

    // Stage input into the dedicated vector-aligned input buffer.
    for (i = 0; i < N_HW; i++)
        INP_BUFF[i] = INPUT_DATA[i];

    // Stage coeff (cwproj-style: source from .rodata into vector-aligned
    // working buffer that the asm will read).
    COEFF_BUFF[0] = COEFF_DATA[0];
    COEFF_BUFF[1] = COEFF_DATA[1];

    // Measure only the kernel body (honest cycle count, not whole-program).
    KCYC_INIT();
    KCYC_START();
    phcom_asm((void *)OUT_BUFF, (void *)INP_BUFF, (void *)COEFF_BUFF, LINES);
    KCYC_STOP_PRINT();

    return vspa_array_cmp((const unsigned *)OUT_BUFF,
                          (const unsigned *)REF_DATA,
                          N_CPLX);
}
