// SPDX-License-Identifier: BSD-3-Clause
// resample_ddc_interp / decimator_2x_8_Taps_asm end-to-end test harness.
//
// Buffer wiring mirrors the cosim driver `compute_decim_2x_8tap.c`
// (which is bit-exactly cross-validated against the DFE_ref pipeline)
// and matches the asm's expectations:
//
//   - pIn      : SM16 complex input, vector aligned, length = N_IN
//   - pOut     : SM16 complex output, vector aligned, length = N_IN/2
//   - pTaps    : 8 float32 taps (2xdown_coeff), 128-byte aligned
//   - filtState: 32 cfixed16_t history slots, 128-byte aligned, BSS-zeroed
//   - n_samples: must be a multiple of 64, >= 64. Internally:
//                  g0 = n_samples >> 6     (line count)
//                  setB.loop g0, 8         (g0 outer iterations)
//
// For the first block with BSS-zeroed state, the asm reads zero filter
// history -> Python oracle matches by passing inp_hist=zeros(FLT_LEN-1).

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <vspa/intrinsics.h>
#include "test_utils.h"

#define NUM_TAPS    8
#define STATE_LEN   32                        // cfixed16_t samples (history buf)
#define N_IN        128                       // complex input samples (mult of 64)
#define N_OUT       (N_IN / 2)                // 2x decimation -> 64 complex out

// 2xdown_coeff (8-tap symmetric LPF). float32 bit patterns; identical to the
// taps embedded in compute_decim_2x_8tap.c (the cosim driver) so asm and
// oracle see the same float32 bit-pattern set.
static const uint32_t FILTER_TAPS_U32[NUM_TAPS] = {
    0xBE0263BE, 0xBDE8A4F0, 0x3EA45618, 0x3F5B3BFF,
    0x3F5B3BFF, 0x3EA45618, 0xBDE8A4F0, 0xBE0263BE
};

// Input data generated by gen_vectors.py (interleaved SM16 re,im,...).
static const int16_t INPUT_DATA[2 * N_IN] = {
#include "vectors/input.hex"
};

// Bit-exact reference produced by r_decimator_2x with 8 taps and zero history.
static const int16_t REF_DATA[2 * N_OUT] = {
#include "vectors/ref.hex"
};

// Vector-aligned working buffers. `static` puts them in .bss -> zero on entry.
_VSPA_VECTOR_ALIGN static int16_t  INP_BUFF[2 * N_IN];
_VSPA_VECTOR_ALIGN static int16_t  OUT_BUFF[2 * N_OUT];
_VSPA_VECTOR_ALIGN static int16_t  STATE_BUFF[2 * STATE_LEN];
_VSPA_VECTOR_ALIGN static uint32_t TAPS_BUFF[NUM_TAPS];

// Asm entry. cfixed16_t* is binary-compatible with int16_t pairs.
extern void decimator_2x_8_Taps_asm(void *pOut, void *pIn, float *pTaps,
                                    void *filtState, unsigned int n_samples);

int main(void)
{
    int i;

    // Stage input and taps into vector-aligned, zero-padded buffers.
    for (i = 0; i < 2 * N_IN; i++)
        INP_BUFF[i] = INPUT_DATA[i];
    for (i = 0; i < NUM_TAPS; i++)
        TAPS_BUFF[i] = FILTER_TAPS_U32[i];

    // STATE_BUFF and OUT_BUFF stay BSS-zero. Asm reads zero filter history
    // from STATE_BUFF; this matches inp_hist=zeros(FLT_LEN-1) in Python.

    // Measure only the kernel body (honest cycle count, not whole-program).
    KCYC_INIT();
    KCYC_START();
    decimator_2x_8_Taps_asm((void *)OUT_BUFF,
                            (void *)INP_BUFF,
                            (float *)TAPS_BUFF,
                            (void *)STATE_BUFF,
                            (unsigned)N_IN);
    KCYC_STOP_PRINT();

    return vspa_array_cmp((const unsigned *)OUT_BUFF,
                          (const unsigned *)REF_DATA,
                          N_OUT);
}
