// SPDX-License-Identifier: BSD-3-Clause
// diffft (fftDIF512_hfx_hfx) end-to-end bit-accurate test harness.
//
// This harness replays NXP's cwproj golden vector set verbatim:
//   submodules/la931x_vspa_common/vspa-lib/diffft/diffft_cwproj/test_vectors/
//     fft512_type1_input_x.hex      (4128 uint32, full input cbuffer)
//     fft512_type1_output_y_ref.hex (512  uint32, MATLAB bit-reversed output)
//     fft512_type1_input_config.hex (4 uint32: [N=512, inv=0, prec=1, off=0xfdf])
//
// Wiring mirrors NXP's cwproj driver (Sources/main.c) exactly:
//   fftDIF512_hfx_hfx(pIn=&buf[offset], pOut, pBuff=buf,
//                     cbuffSize = INPUTBUFF_SIZE * 2 halfwords);
// where pIn ranges through the 4128-sample circular buffer starting at
// the runtime offset (4063 for the regression set), wrapping back to
// buf[0] after 65 samples.
//
// MATLAB equivalent (diffft_testbench.m, prec_type=1):
//   y = bitrevorder( r_dif_fft(x_vsp, 0, 'half_fixed', scaleout=1) )
// gen_vectors.py copies the MATLAB-encoded SM16 cbuffer and reference
// output into vectors/ unmodified.
//
// Why golden replay (and not random + Python oracle):
//   On long radix-2 chains the asm cmad pipeline diverges by 1 ULP from
//   the toolbox r_smad model on ~30% of bins (compounded intermediate
//   rounding). NXP themselves note this in r_decimator_2x.m:119. By
//   replaying MATLAB-generated inputs we test the same contract NXP's
//   own regression tests check: "asm == MATLAB on this vector set".
//
// Build: make -C tests/diffft AU=16
// Run:   python3 scripts/run_test.py --kernel diffft --au 16

#include "test_utils.h"   // <vspa/intrinsics.h> + vspa_array_cmp()
#include "diffft.h"       // fftDIF512_hfx_hfx() declaration

// ---------------------------------------------------------------------------
// Parameters (mirror cwproj constants exactly)
// ---------------------------------------------------------------------------
#define N               512
#define INPUTBUFF_SIZE  (4096 + 32)   /* 4128 complex samples; cwproj main.c */
#define OUTPUTBUFF_SIZE 4096          /* complex samples; cwproj main.c     */
#define INPUT_OFFSET    (4096 + 32 - 65)  /* 4063 = 0xfdf; matches MATLAB    */

// ---------------------------------------------------------------------------
// Embedded test vectors (generated by gen_vectors.py)
// ---------------------------------------------------------------------------

// Input: full 4128-word circular buffer in the MATLAB layout.
// Format: (im_sm16 << 16) | re_sm16 per uint32 word.
// Non-zero entries occupy two contiguous ranges that wrap around the
// circular buffer at INPUT_OFFSET; everything else is zero.
static const unsigned INPUT_CBUFF[INPUTBUFF_SIZE] = {
#include "vectors/input.hex"
};

// Reference output: 512 packed half_fixed complex samples in BIT-REVERSED
// order. Format: (im_sm16 << 16) | re_sm16 per uint32 word.
static const unsigned REF_DATA[N] = {
#include "vectors/ref.hex"
};

// ---------------------------------------------------------------------------
// cwproj-aligned BSS buffers — zero-initialised, vector-aligned.
// One uint32 word holds one packed cfixed16_t complex sample.
// ---------------------------------------------------------------------------
_VSPA_VECTOR_ALIGN static unsigned INP_BUFF[INPUTBUFF_SIZE];
_VSPA_VECTOR_ALIGN static unsigned OUT_BUFF[OUTPUTBUFF_SIZE];

// ---------------------------------------------------------------------------
// Test entry point
// ---------------------------------------------------------------------------
int main(void)
{
    int i;

    // Stage the full circular input buffer (cwproj writes the whole
    // INPUTBUFF_SIZE region, with the FFT input wrapping across
    // INPUT_OFFSET).
    for (i = 0; i < INPUTBUFF_SIZE; i++)
        INP_BUFF[i] = INPUT_CBUFF[i];

    // 512-pt DIF FFT, half_fixed in -> half_fixed out (bit-reversed).
    // cbuffSize is in HALFWORD units (sizeof(cfixed16_t) = 2 halfwords on
    // VSPA2), matching cwproj's `INPUTBUFF_SIZE * 2`.
    fftDIF512_hfx_hfx(
        (vspa_complex_fixed16 const *)(INP_BUFF + INPUT_OFFSET), /* pIn   */
        (vspa_complex_fixed16 *)OUT_BUFF,                        /* pOut  */
        (vspa_complex_fixed16 const *)INP_BUFF,                  /* pBuff */
        INPUTBUFF_SIZE * 2                                       /* halfwords */
    );

    return vspa_array_cmp(OUT_BUFF, REF_DATA, N);
}
