// SPDX-License-Identifier: BSD-3-Clause
// fir33 (firFilterReal) end-to-end bit-accurate test harness.
//
// Buffer layout mirrors NXP's cwproj driver
// (submodules/.../fir33/fir33_cwproj/Sources/main.c) so the asm sees
// identical inputs and a clean (BSS-zeroed) wrap-around region:
//
//   fixed16_t  taps_buffer[256]    __align_vec;            // 256 halfwords
//   cfixed16_t x_buffer[2048+128]  __align_vec;            // M + 128 complex
//   cfixed16_t y_buffer[2048]      __align_vec, .ibss;     // M complex
//
// pIn = x_buffer + IN_OFFSET (= 9 complex prefix words). The 9 prefix
// slots and the 128 trailing slots are BSS-zeroed; the asm's circular
// VRA wrap-around therefore reads zeros for any out-of-data accesses.
//
// Build: make -C tests/fir33 AU=16
// Run:   python3 scripts/run_test.py --kernel fir33 --au 16
//
// Why our previous harness failed: x_buf was declared `unsigned` (no
// vector-alignment attribute) and sized exactly IN_OFFSET+M+L-1, so any
// trailing-slot prefetch beyond the data window read garbage from
// adjacent globals. Mirroring cwproj's __align_vec + 128-element pad
// fixes the wiring.

#include "test_utils.h"   // includes <vspa/intrinsics.h>, vspa_array_cmp()

// Define VSPA fixed-point types needed by fir.h.
// Cannot include vcpu.h directly — it re-declares main() as void __noreturn.
// __fx16 is a built-in VSPA compiler type available after <vspa/intrinsics.h>.
typedef __fx16 fixed16_t;
typedef struct { fixed16_t real; fixed16_t imag; } cfixed16_t;

#include "fir.h"          // firFilterReal() declaration

// ---------------------------------------------------------------------------
// Parameters (derived from firFilter_input_config.hex):
//   cfg[0] = 0x800 = 2048 = M   (datSz  — number of complex output samples)
//   cfg[1] = 0x21  = 33   = L   (tapsSz — number of filter taps)
//   cfg[2] = 0x00  = 0          (type   — 0 = half_fixed)
//   cfg[3] = 0x09  = 9          (inOffset)
//
// Kernel arguments:
//   itDat  = datSz >> 6   = M / 64 = 32
//   itTaps = tapsSz - 11  = L - 11 = 22
// ---------------------------------------------------------------------------
#define M          2048
#define L          33
#define IN_OFFSET  9      // cfixed16_t complex words of zero prefix before pIn
#define IT_DAT     32     // M / 64
#define IT_TAPS    22     // L - 11

// cwproj sizes
#define TAPS_BUF_LEN    256                // halfwords (fixed16_t)
#define X_BUF_LEN_CPLX  (M + 128)          // 2176 complex (M + lookahead pad)
#define Y_BUF_LEN_CPLX  M                  // 2048 complex

// ---------------------------------------------------------------------------
// Embedded test vectors (generated by gen_vectors.py)
// ---------------------------------------------------------------------------

// Filter taps: fixed16_t (uint16) values in reversed order [h[L-1] ... h[0]],
// L_PAD = 34 entries; the rest of taps_buffer stays zero.
#define L_PAD 34
static const unsigned short TAPS_DATA[L_PAD] = {
#include "vectors/taps.hex"
};

// Input data — M+L-1 = 2080 complex samples (uint32 sign-magnitude packed).
static const unsigned INPUT_DATA[M + L - 1] = {
#include "vectors/x_input.hex"
};

// Reference output: M complex samples (uint32 SM packed).
static const unsigned y_ref[M] = {
#include "vectors/y_ref.hex"
};

// ---------------------------------------------------------------------------
// Buffers — match cwproj's main.c layout exactly:
//   - declared static (→ .bss, zero-initialised at boot)
//   - vector-aligned via _VSPA_VECTOR_ALIGN
//   - oversized to leave a BSS-zero pad on both ends so the asm's vector
//     prefetch / VRA wrap-around always reads zeros, never garbage.
// ---------------------------------------------------------------------------
_VSPA_VECTOR_ALIGN static unsigned short taps_buffer[TAPS_BUF_LEN];
_VSPA_VECTOR_ALIGN static unsigned       x_buffer[X_BUF_LEN_CPLX];
_VSPA_VECTOR_ALIGN static unsigned       y_buffer[Y_BUF_LEN_CPLX];

// ---------------------------------------------------------------------------
// Test entry point
// ---------------------------------------------------------------------------
int main(void)
{
    int i;

    // Stage taps into taps_buffer[0..L_PAD-1]; tail stays zero.
    for (i = 0; i < L_PAD; i++)
        taps_buffer[i] = TAPS_DATA[i];

    // Stage input data into x_buffer[IN_OFFSET .. IN_OFFSET + (M+L-1) - 1].
    // The leading IN_OFFSET=9 slots remain zero (BSS), as does the trailing
    // 128-slot pad — that mirrors cwproj's main.c initial state.
    for (i = 0; i < (int)(M + L - 1); i++)
        x_buffer[IN_OFFSET + i] = INPUT_DATA[i];

    // Run NXP half-fixed FIR kernel (cwproj-equivalent call).
    // Measure only the kernel body (honest cycle count, not whole-program).
    KCYC_INIT();
    KCYC_START();
    firFilterReal((cfixed16_t *)(x_buffer + IN_OFFSET),
                  (cfixed16_t *)y_buffer,
                  (fixed16_t *)taps_buffer,
                  IT_DAT,
                  IT_TAPS);
    KCYC_STOP_PRINT();

    // Bit-exact comparison — prints PASS / FAIL line for run_test.py.
    return vspa_array_cmp(y_buffer, y_ref, M);
}
