// SPDX-License-Identifier: BSD-3-Clause
// nco_phase_ramp end-to-end test harness — buffer layout mirrors NXP's
// cwproj driver (submodules/.../nco_phase_ramp/nco_phase_ramp_cwproj/
// Sources/main.c).
//
// The asm `phase_ramp_gen(out_p, gain_cpx_p, phase_ramp, phase_init, num_lines)`
// generates an NCO sequence and applies a complex gain in one pass:
//   out[k] = gain * exp(-j * 2π · (phase_ramp/2^32) · (phase_init + k))
// for k = 0 .. 32*num_lines - 1.
//
// out_p is complex half-precision (cfloat16_t — 2 halfwords / sample).
// gain_cpx_p is complex single-precision (cfloat32_t — 4 halfwords).
// Reference is generated by the bit-exact Python r_nco / r_smad / r_half_flt
// oracle (verify_nco_phase_ramp.py is green against NXP golden vectors).

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <vspa/intrinsics.h>
#include "test_utils.h"

extern void phase_ramp_gen(void *out_p, void *gain_cpx_p,
                           int32_t phase_ramp, int32_t phase_init,
                           uint32_t num_lines);

// ---- must mirror gen_vectors.py ----
#define NUM_LINES      2
#define SAMP_PER_LINE  32
#define N_CPLX         (NUM_LINES * SAMP_PER_LINE)
#define N_HW_OUT       (2 * N_CPLX)        // 2 halfwords / complex-half sample
#define N_HW_GAIN      4                   // cfloat32_t = 2 × float32 = 4 halfwords

// norm_freq=0.0102, initial_phase=-122 (matches cwproj test_bench.m).
//   round(0.0102 * 2^32) = 43806619 = 0x029C779A
//   int32(-122) reinterpreted as uint32 = 0xFFFFFF86
// Keep these in lock-step with gen_vectors.py — both encode the same
// constants, so any drift would silently desync the harness.
#define PHASE_RAMP   ((int32_t)0x029C779A)
#define PHASE_INIT   ((int32_t)0xFFFFFF86)

// Complex gain encoded as float32 halves loaded from input.hex.
static const int16_t GAIN_DATA[N_HW_GAIN] = {
#include "vectors/input.hex"
};
static const int16_t REF_DATA[N_HW_OUT] = {
#include "vectors/ref.hex"
};

// Mirror cwproj: vector-aligned, BSS-resident (zero-initialised) buffers.
// The output is declared as cfloat16_t[256] in cwproj — we size to actual
// N_CPLX. The gain buffer needs vector alignment because the asm loads it
// with `ld [a1]+0` (a full DMEM line load).
_VSPA_VECTOR_ALIGN static int16_t PHASE_RAMP_OUT_BUFF[N_HW_OUT];
_VSPA_VECTOR_ALIGN static int16_t GAIN_BUFF[__AU_COUNT__ * 4];   // one DMEM line, zero padded

int main(void)
{
    int i;

    // Stage gain into the line-aligned scratch buffer (rest stays zero).
    for (i = 0; i < N_HW_GAIN; i++)
        GAIN_BUFF[i] = GAIN_DATA[i];

    // Measure only the kernel body (honest cycle count, not whole-program).
    KCYC_INIT();
    KCYC_START();
    phase_ramp_gen((void *)PHASE_RAMP_OUT_BUFF,
                   (void *)GAIN_BUFF,
                   PHASE_RAMP,
                   PHASE_INIT,
                   (uint32_t)NUM_LINES);
    KCYC_STOP_PRINT();

    // Compare as packed uint32 words (re_u16 | im_u16<<16).
    return vspa_array_cmp((const unsigned *)PHASE_RAMP_OUT_BUFF,
                          (const unsigned *)REF_DATA,
                          N_CPLX);
}
