// SPDX-License-Identifier: BSD-3-Clause
// cycShiftFD_asm end-to-end test harness — buffer layout mirrors NXP's
// cwproj driver (submodules/.../cycShiftFD/cycShiftFD_cwproj/src/main.c)
// so the asm sees identical inputs and writes the same outputs.
//
// `cycShiftFD_asm(in_p, out_p, shift, length)` performs
//   y[k] = x[k] * exp(+2πj * (round(shift * 2^32 / length) / 2^32) * k)
// on `length` cfloat16 samples (16-bit complex half-precision floats).
// Reference is generated by the bit-exact Python r_nco/r_smad/r_half_flt
// oracle (verify_cycShiftFD.py is green against 30/30 NXP golden TCs).

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <vspa/intrinsics.h>
#include "test_utils.h"

typedef struct { int16_t re; int16_t im; } cfloat16_t;

extern void cycShiftFD_asm(cfloat16_t *in_p, cfloat16_t *out_p,
                           int shift, int length);

// Match gen_vectors.py config (must keep in sync).
#define N        64    // complex samples (= length arg)
#define SHIFT    8     // matches cwproj TC002/TC003

// One u32 word per complex sample: (im_bits << 16) | re_bits, packed f16.
static const unsigned INPUT_DATA[N] = {
#include "vectors/input.hex"
};
static const unsigned REF_DATA[N] = {
#include "vectors/ref.hex"
};

// Mirror cwproj: vector-aligned, BSS-resident (zero-initialised) buffers.
// cwproj uses TEST_MAX_LEN=2048; we size to N (fully covers our config).
_VSPA_VECTOR_ALIGN static cfloat16_t INP_BUFF[N];
_VSPA_VECTOR_ALIGN static cfloat16_t OUT_BUFF[N];

int main(void)
{
    int i;

    // Stage input into the dedicated vector-aligned input buffer (cwproj
    // mem_copy). Reading from .rodata-resident INPUT_DATA into a vector
    // line-aligned BSS buffer mirrors the asm's expected DMEM layout.
    for (i = 0; i < N; i++) {
        unsigned w = INPUT_DATA[i];
        INP_BUFF[i].re = (int16_t)(w & 0xFFFFu);
        INP_BUFF[i].im = (int16_t)((w >> 16) & 0xFFFFu);
    }

    // Measure only the kernel body (honest cycle count, not whole-program).
    KCYC_INIT();
    KCYC_START();
    cycShiftFD_asm(INP_BUFF, OUT_BUFF, SHIFT, N);
    KCYC_STOP_PRINT();

    return vspa_array_cmp((const unsigned *)OUT_BUFF,
                          (const unsigned *)REF_DATA,
                          N);
}
