// SPDX-License-Identifier: BSD-3-Clause
// ditfft (fftDIT512_hfl) end-to-end bit-accurate test harness.
//
// Wiring mirrors NXP's cwproj driver:
//   submodules/la931x_vspa_common/vspa-lib/ditfft/ditfft_cwproj/Sources/main.c
//
// cwproj allocates a vector-aligned BSS input buffer of 4096+32 unsigned ints,
// loads bit-reversed input data into it (with a configurable offset, default 31),
// and calls fftDIT512_hfl(input_buffer + offset, output_buffer).
//
// MATLAB equivalent: y = fft(x)  (type0, scale_out=1 → per-stage 1/2 scaling
// and Q15 quantisation).  Reference oracle: r_dit_fft(x_natural,
//   inv_flag=0, prec_type='half_fixed', scale_out=1) — the oracle takes
// natural-order x and bit-reverses internally; gen_vectors.py writes the
// asm-side input bit-reversed because the asm reads its input in natural
// memory order.
//
// Build: make -C tests/ditfft AU=16
// Run:   python3 scripts/run_test.py --kernel ditfft --au 16

#include "test_utils.h"   // <vspa/intrinsics.h> + vspa_array_cmp()
#include "ditfft.h"       // fftDIT512_hfl() declaration

// Do NOT include vcpu.h — re-declares main() as void __noreturn.

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------
#define N            512
#define INP_BUFF_LEN (4096 + 32)   // matches cwproj input_buffer[]
#define OUT_BUFF_LEN 4096          // matches cwproj output_buffer[]
#define INPUT_OFFSET 0             // word offset into INP_BUFF; 0 keeps the
                                   // harness self-contained (cwproj uses 31
                                   // to exercise alignment, not correctness)

// ---------------------------------------------------------------------------
// ifftDITScratchBuffer — declared extern in ditfft.h; only the IFFT variants
// touch it, but the linker still needs a definition.
// ---------------------------------------------------------------------------
unsigned int ifftDITScratchBuffer[4096] _VSPA_VECTOR_ALIGN;

// ---------------------------------------------------------------------------
// Embedded test vectors (generated by gen_vectors.py).  Each unsigned word is
//   (im_u16 << 16) | re_u16
// where the input is packed truncated-IEEE float16 in *bit-reversed* order
// (the asm reads bit-reversed input in natural address order) and the
// reference is packed VSPA SM16 in natural order.
// ---------------------------------------------------------------------------
static const unsigned INPUT_DATA[N] = {
#include "vectors/input.hex"
};

static const unsigned REF_DATA[N] = {
#include "vectors/ref.hex"
};

// ---------------------------------------------------------------------------
// BSS-resident, vector-aligned working buffers — same shape as cwproj.
// ---------------------------------------------------------------------------
_VSPA_VECTOR_ALIGN static unsigned INP_BUFF[INP_BUFF_LEN];
_VSPA_VECTOR_ALIGN static unsigned OUT_BUFF[OUT_BUFF_LEN];

// ---------------------------------------------------------------------------
int main(void)
{
    int i;

    // Stage input into INP_BUFF at INPUT_OFFSET; tail stays BSS-zero.
    for (i = 0; i < N; i++)
        INP_BUFF[INPUT_OFFSET + i] = INPUT_DATA[i];

    // 512-point DIT FFT: float16 in, half_fixed (SM16) out.
    fftDIT512_hfl((vspa_complex_float16 const *)(INP_BUFF + INPUT_OFFSET),
                  (vspa_complex_fixed16 *)OUT_BUFF);

    // Bit-exact uint32 comparison.  vspa_array_cmp prints the first mismatch
    // and a final "PASS"/"FAIL" line that scripts/run_test.py parses.
    return vspa_array_cmp(OUT_BUFF, REF_DATA, N);
}
